name: 'Check SQL Tables'
description: 'Check the SQL table if user have or not'
inputs:
  api_key:
    description: 'The API key for Plugin'
    required: true
outputs:
  status:
    description: 'The status of the deployment'
runs:
  using: 'node20'
  main: 'index.js'